networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

x-rmq-common: &common-config
  networks:
    - rabbitnet
  build: rmq
  mem_limit: 8gb
  ulimits:
    nofile:
      soft: 65536
      hard: 131072

services:
  rmq0:
    <<: *common-config
    hostname: rmq0
    volumes:
      - ./data/rmq0:/var/lib/rabbitmq/mnesia
      - ./log/rmq0:/var/log/rabbitmq
    ports:
      # HOST:CONTAINER
      - 8872:15672
      - 15692:15692
  rmq1:
    <<: *common-config
    hostname: rmq1
    volumes:
      - ./data/rmq1:/var/lib/rabbitmq/mnesia
      - ./log/rmq1:/var/log/rabbitmq
    ports:
      # HOST:CONTAINER
      - 8873:15672
      - 15693:15692
  rmq2:
    <<: *common-config
    hostname: rmq2
    volumes:
      - ./data/rmq2:/var/lib/rabbitmq/mnesia
      - ./log/rmq2:/var/log/rabbitmq
    ports:
      # HOST:CONTAINER
      - 8874:15672
      - 15694:15692
  perf-test-producer:
    image: pivotalrabbitmq/perf-test:latest
    networks:
      - rabbitnet
    command:
      - --uri=amqp://haproxy
      - --servers-startup-timeout=45
      - --heartbeat=5
      - --producers=1
      - --consumers=0
      - --exchange=update.exchange.number1
      - --routing-key=key1
      - --predeclared
      - --rate=1
      - --json-body
      - --size=1000
    depends_on:
      - rmq0
      - rmq1
      - rmq2
      - haproxy
    restart: on-failure
  perf-test-consumer:
    image: pivotalrabbitmq/perf-test:latest
    networks:
      - rabbitnet
    command:
      - --uri=amqp://haproxy
      - --servers-startup-timeout=45
      - --heartbeat=5
      - --producers=0
      - --consumers=4
      - --exchange=update.exchange.number1
      - --type=topic
      - --routing-key=key1
      - --exclusive
      - --auto-delete=true
      - --qos=1
    depends_on:
      - rmq0
      - rmq1
      - rmq2
      - haproxy
    restart: on-failure
  haproxy:
    image: haproxy:latest
    networks:
      - rabbitnet
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq0
      - rmq1
      - rmq2
    ports:
      # HOST:CONTAINER
      - 15672:15672
      - 5672:5672
