networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

x-common: &common-config
  networks:
    - rabbitnet
  mem_limit: 8gb
  ulimits:
    nofile:
      soft: 65536
      hard: 131072

services:
  stream-perf-test:
    image: pivotalrabbitmq/stream-perf-test:latest
    networks:
      - rabbitnet
    command:
      - --uris rabbitmq-stream://rmq0:5552,rabbitmq-stream://rmq1:5552,rabbitmq-stream:rmq2:5552
      - --producers 1
      - --consumers 1
      - --rate 100
      - --delete-streams
      - --max-age PT30S
    restart: on-failure
